## Assignment 2

**Focus**: data modeling and evaluation and comparison of models

**Libraries:**

- `tidyverse`
- `tidymodels`
- `skimr`

This assignment continues from Assignment 1 so it is essential that you complete your Assignment 1 before this step.
Copy your code from Assignment 1 under the section 
### Assignment 1

1. Put the heading 
### Assignment 2

Use `set.seed(2021)`

Set metrics for the models. Use RMSE for `metric_set()`

Write a sentence explaining what RMSE is and why to use it in this case.

Write a sentence explaining the use of `metric_set()`

2. Read further about `control_grid()` function. What does it do?

What does the following parameters do?

```
save_pred = TRUE
save_workflow = TRUE
extract = extract_model
```

Use them in your code to seve your `control_grid()` as `grid_control`

3. With `train` dataset use `vfold_cv(5)`to save it to `train_fold5`
Write a sentence what `vfold_cv()` function does and why we use it here

4. Set your model using `boost_tree()` model from `tidymodels` https://parsnip.tidymodels.org/reference/boost_tree.html and `xgboost` engine

  Use "regression"
  and the following list of parameters:
  
  Write a sentence for each explaining what they do:
  
 ```
 mtry = tune(),
 trees = tune(),
 learn_rate = tune())
 ```

5. (taken out)

6. Set up the `workflow()` and use `recipe_xg` recipe you created in assignment 1 and the model you created in the previous step

7. Run your workflow using the following code and save the results under xg_tune:

```
tune_grid(train_fold5,
            metrics = mset,
            control = grid_control,
            grid = crossing(mtry = c(7),
                            trees = seq(250, 1500, 25),
                            learn_rate = c(.008, .01)))

```

Write 3 sentences explaining what the code does.

8. Use `autoplot()` function to view the results `xg_tune`

9. Use `collect_metrics()` to view the results. Arrange using `mean`

10. Finalize and save your results under `xg_fit` for your model by using create workflow `xg_wf` with :

  ```
  finalize_workflow(select_best(xg_tune)) %>%
  fit(train)
  ```
  
Write 2 sentences explaining what the code does.

11. Use the following code and write a sentence for each function explaining what it does:

```
xg_fit %>%
augment(test) %>%
rmse(price, .pred)

importances <- xgboost::xgb.importance(model = xg_fit$fit$fit$fit)

holdout<-read_csv("https://raw.githubusercontent.com/maria-pro/bco6008/main/train_airbnb.csv")

xg_fit %>%
    augment(holdout) %>%
    mutate(.pred = exp(.pred) - 1) %>%
    select(id, price = .pred) %>%
  write_csv("xg_attempt.csv")
```

12 Run the following code and write 2 sentences explaining what you see on the plot:

```
importances %>%
mutate(Feature = fct_reorder(Feature, Gain)) %>%
ggplot(aes(Gain, Feature)) +
geom_col()
```

13. Develop an alternative model using `linear_reg()` with `penatly=tune()` and `glmnet` engine. Save it as `lin_mod`

14. Create a new workflow for this model using `lin_rec` and `lin_mod`. Save it as `lin_wf`

15. Run your workflow with the following code

```
lin_tune <- lin_wf %>%
  tune_grid(train_fold5,
            metrics = mset,
            control = grid_control,
            grid = crossing(penalty = 10 ^ seq(-7, -1, .1),
                            threshold = .001
                            )
```

Write a paragraph exlaining this step.

As in the previous model use `autoplot(lin_tune)`

Also use

```
lin_tune %>%
collect_metrics() %>%
arrange(mean)
```
 
 Write a sentence explaining the what you see

16. Run the following code and write a paragraph expalining the results and comparing the two models

```
lin_fit <- lin_wf %>%
  finalize_workflow(select_best(lin_tune)) %>%
  fit(train)
lin_fit %>%
  augment(test) %>%
  rmse(.pred, price)
```

17. Write a conclusion with your recommendations on which model to use and insights you have from the data



